/**
 * API contract for progressive AI hints during an exam.
 *
 * The API never returns provider errors, API keys, or model names to the client.
 * Static hint content lives in the database; interactive hints are generated by
 * the backend-only hint-engine service and returned as plain guidance text.
 */
export const HINT_DELIVERY_TYPES = ["STATIC", "INTERACTIVE"] as const;
export type HintDeliveryType = (typeof HINT_DELIVERY_TYPES)[number];

export const HINT_USAGE_STATUSES = ["REQUESTED", "UNLOCKED", "CONSUMED"] as const;
export type HintUsageStatus = (typeof HINT_USAGE_STATUSES)[number];

export interface HintStageView {
  stageNumber: number;
  title: string | null;
  description: string | null;
  deliveryType: HintDeliveryType;
  unlockDelaySeconds: number;
  /** The student may request this stage now (progression + unlock delay satisfied). */
  available: boolean;
  /** Why it is not yet available, for the UI. `null` when available or already used. */
  lockedReason: string | null;
  /**
   * Server-authoritative instant (ISO 8601) this stage's time-delay clears, so the
   * client can render a live countdown without polling. `null` unless the stage is
   * blocked purely on `unlockDelaySeconds` (i.e. the previous-stage gate is already
   * satisfied) and not yet available.
   */
  unlockAt: string | null;
  /** Set once the stage has been requested/consumed by this session. */
  status: HintUsageStatus | null;
  /** Hint text, present only once the stage has been consumed. */
  content: string | null;
  requestedAt: string | null;
}

/** `GET /api/v1/student/sessions/:sessionId/questions/:questionId/hints`. */
export interface QuestionHintsView {
  questionId: string;
  stages: HintStageView[];
}

/** `POST /api/v1/student/sessions/:sessionId/questions/:questionId/hints`. */
export interface HintRequestResult {
  stageNumber: number;
  deliveryType: HintDeliveryType;
  status: HintUsageStatus;
  content: string;
  source: "static" | "ai";
}
