/**
 * API contract for progressive AI hints during an exam.
 *
 * The API never returns provider errors, API keys, or model names to the client.
 * Static hint content lives in the database; interactive hints are generated by
 * the backend-only hint-engine service and returned as plain guidance text.
 */
export const HINT_DELIVERY_TYPES = ["STATIC", "INTERACTIVE"] as const;
export type HintDeliveryType = (typeof HINT_DELIVERY_TYPES)[number];

export const HINT_USAGE_STATUSES = ["REQUESTED", "UNLOCKED", "CONSUMED"] as const;
export type HintUsageStatus = (typeof HINT_USAGE_STATUSES)[number];

export interface HintStageView {
  stageNumber: number;
  title: string | null;
  description: string | null;
  deliveryType: HintDeliveryType;
  /**
   * Legacy stage configuration, echoed for compatibility only. Escalation is
   * gated on the student's persisted execution evidence (unsuccessful evaluated
   * attempts), not on elapsed time - this value no longer controls availability.
   */
  unlockDelaySeconds: number;
  /** The student may request this stage now (progression + evidence policy satisfied). */
  available: boolean;
  /**
   * Why it is not yet available, for the UI - e.g. "Submit an attempt first".
   * `null` when available or already used.
   */
  lockedReason: string | null;
  /**
   * Kept for API compatibility; always `null` since escalation stopped being
   * time-gated (there is no instant to count down to). Clients may still render
   * a countdown if a non-null value ever appears.
   */
  unlockAt: string | null;
  /** Set once the stage has been requested/consumed by this session. */
  status: HintUsageStatus | null;
  /** Hint text, present only once the stage has been consumed. */
  content: string | null;
  requestedAt: string | null;
}

/** `GET /api/v1/student/sessions/:sessionId/questions/:questionId/hints`. */
export interface QuestionHintsView {
  questionId: string;
  stages: HintStageView[];
}

// ---------------------------------------------------------------------------
// Execution evidence handed to hint generation (API -> hint-engine)
// ---------------------------------------------------------------------------

/**
 * One attempt as the hint generator may know it. Counts only - never test
 * content. `PENDING` = still being graded; `NOT_EVALUATED` = the grader itself
 * failed (sandbox unavailable, evaluator error), which says nothing about the
 * student's code and must not be read as a failed attempt.
 */
export type HintAttemptOutcome = "PASSED" | "FAILED" | "PENDING" | "NOT_EVALUATED";

export interface HintAttemptEvidence {
  attemptNumber: number;
  outcome: HintAttemptOutcome;
  /** Graded (non-SKIPPED) cases passed / total; `null` unless evaluated. */
  testsPassed: number | null;
  testsTotal: number | null;
  /** How many HIDDEN cases did not pass - a count only, never which or why. */
  hiddenTestsFailed: number | null;
}

/**
 * A failing VISIBLE test case from the latest evaluated attempt: exactly the
 * data the student already sees in their own result view (`StudentTestResult`),
 * plus a bounded excerpt of their program's own stderr for that input.
 * Hidden cases are never represented here.
 */
export interface HintVisibleFailure {
  name: string | null;
  status: "FAILED" | "ERROR" | "TIMEOUT" | "SKIPPED";
  input: string;
  expectedOutput: string;
  actualOutput: string;
  errorOutput: string | null;
}

/**
 * Sanitized, bounded execution evidence for one session + question. Built by
 * the API from persisted `Submission` / `EvaluationRun` / `TestCaseResult`
 * rows; the hint-engine only ever sees this shape. No identifiers, no hidden
 * test data, no grader internals.
 */
export interface HintExecutionEvidence {
  /** Attempts whose evaluation run COMPLETED. */
  evaluatedAttempts: number;
  /** Evaluated attempts with at least one case not PASSED. */
  unsuccessfulAttempts: number;
  /** Attempts still queued/running. */
  pendingAttempts: number;
  /** Attempts the grader could not evaluate (infrastructure, not the student). */
  notEvaluatedAttempts: number;
  /** Outcome of the most recent evaluated attempt; `null` when none completed. */
  latestOutcome: "PASSED" | "FAILED" | null;
  /** The most recent attempts, oldest first (bounded). */
  attempts: HintAttemptEvidence[];
  /** Visible failing cases of the latest evaluated attempt (bounded). */
  latestVisibleFailures: HintVisibleFailure[];
}

/** `POST /api/v1/student/sessions/:sessionId/questions/:questionId/hints`. */
export interface HintRequestResult {
  stageNumber: number;
  deliveryType: HintDeliveryType;
  status: HintUsageStatus;
  content: string;
  source: "static" | "ai";
}
